### ISSUE TITLE
Credentials via `simple-configuration`

### ISSUE THREAD

**Issue by michel-ds** [guardian/recipes#14]
Wonder whether you could have a look at these lines and see if you can spot any obvious issues, @akash1810 ?
https://github.com/guardian/recipes/blob/d733fab152ca5a58c2763c43bf974ded3832a3b7/app/config/Config.scala#L49-L59

It runs fine in `DEV` but does not seem to run when deployed in `PROD`. 
Nothing in the logs, probably errors out before any logging starts.

**Comment by akash1810** [comment]
I suspect this is a permissions issue; the instance [doesn't have permissions](https://github.com/guardian/recipes/blob/3e292036ad699783afe160b7d2468d87ec5d8567/cloudformation.yaml#L112-L156) to read from `recipes-dist` in S3, you'd want to give it access to that bucket and deploy the change via RiffRaff.

**Comment by michel-ds** [comment]
Good point! I have done so now and can see the change in RiffRaff
` [10:56:28] GetBucketConfigPolicy (AWS::IAM::Policy): CREATE_IN_PROGRESS` but still no joy.

https://github.com/guardian/recipes/blob/beb601d8f759ffb8289d8cf84aa1aed1b06e77ee/cloudformation.yaml#L143-L156

**Comment by michel-ds** [comment]
Now solved. ✅
